language: python
puthon: 3.8
script:
  - cd Lab666
  - pytest
  - cd ..

deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: PolinaK1/Lab666
    branch: dev
    tags: false
