language: python
puthon: 3.8
script:
  - cd PythonApplication1
  - pytest
  - cd ..

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN1
  skip_cleanup: true
  on:
    repo: PolinaK1/Lab666
    branch: master
    tags: false
